/**
 * Demo data for the App Review / demo account (test@cyber7.com).
 *
 * The demo account is served entirely from this in-memory dataset — it never
 * calls ConnectWise. This guarantees the reviewer always sees a populated,
 * fully-working app (list → detail → acknowledge/resolve/notes) with no
 * dependency on live ConnectWise tickets and no risk of a 5xx.
 *
 * Real user/admin accounts are unaffected and continue to get live data.
 */

const DEMO_EMAIL = 'test@cyber7.com';

function isDemoUser(user) {
  return !!user && String(user.email || '').toLowerCase() === DEMO_EMAIL;
}

// List-shape alerts (matches AlertTicket in services/api.ts)
const DEMO_ALERTS = [
  {
    id: 9001,
    client: 'Cyber7',
    companyIdentifier: 'cyber7',
    type: 'Priority 1 - Critical',
    message: 'Ransomware behaviour detected on endpoint FIN-WS-04',
    time: 'Just now',
    status: 'active',
    severity: 'critical',
  },
  {
    id: 9002,
    client: 'Cyber7',
    companyIdentifier: 'cyber7',
    type: 'Priority 2 - High',
    message: 'Multiple failed admin logins from an unrecognised IP',
    time: '12 min ago',
    status: 'active',
    severity: 'high',
  },
  {
    id: 9003,
    client: 'Cyber7',
    companyIdentifier: 'cyber7',
    type: 'Priority 1 - Critical',
    message: 'Phishing email campaign targeting finance team',
    time: '48 min ago',
    status: 'acknowledged',
    severity: 'critical',
  },
  {
    id: 9004,
    client: 'Cyber7',
    companyIdentifier: 'cyber7',
    type: 'Priority 2 - High',
    message: 'Firewall rule violation on network segment B',
    time: '2 hours ago',
    status: 'active',
    severity: 'high',
  },
];

const DEMO_IDS = new Set(DEMO_ALERTS.map((a) => a.id));

function isDemoAlertId(id) {
  return DEMO_IDS.has(Number(id));
}

// Detail-shape objects (matches GET /alerts/:id response)
function buildDemoDetail(alert) {
  return {
    id: alert.id,
    summary: alert.message,
    severity: alert.severity,
    status: alert.status,
    time: new Date().toISOString(),
    company: {
      name: 'Cyber7',
      identifier: 'cyber7',
      contact: 'Security Operations',
      email: 'soc@cyber7.com.au',
      site: 'Head Office',
      addressLine1: '',
      addressLine2: '',
      city: 'Melbourne',
      state: 'VIC',
      zip: '',
      country: 'Australia',
    },
    ticket: {
      board: 'Security Operations',
      status: alert.status === 'resolved' ? 'Closed' : 'In Progress',
      type: 'Security Incident',
      subType: 'Default',
      item: '',
      owner: 'SOC Analyst',
      sla: 'Standard SLA',
      agreement: 'Managed Security Services',
      priority: alert.type,
      priorityId: alert.severity === 'critical' ? 1 : 2,
      impact: 'High',
      urgency: 'High',
      estimatedStartDate: '',
      requiredDate: '',
      slaStatus: 'On Track',
      budgetHours: 4,
      actualHours: 1,
      enteredBy: 'Automated Detection',
      enteredDate: new Date().toISOString(),
      assignedBy: 'SOC',
    },
    notes: [
      {
        id: alert.id * 10 + 1,
        text: 'Alert automatically generated by the Cyber7 detection platform.',
        noteType: 'Discussion',
        member: 'Detection Engine',
        dateCreated: new Date().toISOString(),
        detailDescriptionFlag: true,
        internalAnalysisFlag: false,
        resolutionFlag: false,
      },
    ],
  };
}

function getDemoAlerts() {
  // Return copies so callers can safely merge local state overrides
  return DEMO_ALERTS.map((a) => ({ ...a }));
}

function getDemoDetail(id) {
  const alert = DEMO_ALERTS.find((a) => a.id === Number(id));
  return alert ? buildDemoDetail(alert) : null;
}

module.exports = {
  DEMO_EMAIL,
  isDemoUser,
  isDemoAlertId,
  getDemoAlerts,
  getDemoDetail,
};
